# Generated by Django 3.0.2 on 2020-02-01 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('name_en_us', models.CharField(max_length=16, null=True, unique=True)),
                ('name_de_de', models.CharField(max_length=16, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('name_en_us', models.CharField(max_length=32, null=True, unique=True)),
                ('name_de_de', models.CharField(max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('name_en_us', models.CharField(max_length=32, null=True, unique=True)),
                ('name_de_de', models.CharField(max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chaos_dating.Gender')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaos_dating.Interest')),
            ],
            options={
                'unique_together': {('interest', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chaos_dating.Gender')),
                ('pronoun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chaos_dating.Pronoun')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishes', models.ManyToManyField(to='chaos_dating.Wish')),
            ],
        ),
    ]
