# Generated by Django 3.0.3 on 2020-03-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaos_dating', '0003_profile_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
    ]
